languageCode = "ja"
baseurl = "https://rynotes.com/"
title = "RYNOTES"
disqusShortname = "rynotes"

[Params]
subtitle = "なんちゃって Rails Contributors の日記"
facebook = "https://facebook.com/ojiry"
twitter = "https://twitter.com/ojiry"
github = "https://github.com/ojiry"
showsRSS = true
profile = "/images/profile.png"
copyright = "Written by Ryoji Yoshioka"
# analytics = "UA-XXXXXXXX-X"
# shareThis = "XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX"

[permalinks]
post = "/:year/:month/:day/:filename/"
