baseurl = "https://rynotes.com/"
disqusShortname = "rynotes"
languageCode = "ja"
theme = 'angels-ladder'
title = "RYNOTES"

[Params]
subtitle = "なんちゃって Rails Contributors の日記"
facebook = "https://facebook.com/ojiry"
twitter = "https://twitter.com/ojiry"
github = "https://github.com/ojiry"
showsRSS = true
profile = "/images/profile.png"
copyright = "Written by Ryoji Yoshioka"
tagManager = "GTM-5W6LSJ"
adSense = true

[permalinks]
post = "/:year/:month/:day/:filename/"
