---
- name: install openssl 
  yum: name=openssl-devel state=present

- name: create ssl directory
  file: path=/etc/ssl state=directory

- name: create stg.rynotes.com.key
  shell: openssl genrsa -out stg.rynotes.com.key 2048
  args:
    chdir: /etc/ssl
    creates: stg.rynotes.com.key

- name: create stg.rynotes.com.csr
  shell: openssl req -new -key stg.rynotes.com.key -out stg.rynotes.com.csr -subj '/C=JP/ST=Tokyo/L=Tokyo/O=RYNOTES/OU=Web/CN=stg.rynotes.com'
  args:
    chdir: /etc/ssl
    creates: stg.rynotes.com.csr

- name: create stg.rynotes.com.pem
  shell: openssl x509 -req -signkey stg.rynotes.com.key -in stg.rynotes.com.csr -days 90 -out stg.rynotes.com.pem 
  args:
    chdir: /etc/ssl
    creates: stg.rynotes.com.pem
