---
- name: install requirements package
  yum: name={{ item }} state=present
  with_items:
    - gcc
    - bzip2
    - openssl-devel
    - libyaml-devel
    - libffi-devel
    - readline-devel
    - zlib-devel
    - gdbm-devel
    - ncurses-devel
    - autoconf
    - bison

- name: download rbenv
  git: repo=https://github.com/rbenv/rbenv.git
       dest=/home/deploy/.rbenv
  become_user: deploy

- name: add rbenv/bin to $PATH
  lineinfile: dest=/home/deploy/.bash_profile
              line='export PATH="$HOME/.rbenv/bin:$PATH"'
  become_user: deploy

- name: add rbenv init to .bash_profile
  lineinfile: dest=/home/deploy/.bash_profile
              line='eval "$(rbenv init -)"'
  become_user: deploy

- name: download ruby-build
  git: repo=https://github.com/rbenv/ruby-build.git
       dest=/home/deploy/.rbenv/plugins/ruby-build
  become_user: deploy

- name: install host ruby
  yum: name=ruby state=present

- name: install ruby 2.4.0-dev
  shell: bash -lc "rbenv install 2.4.0-dev"
  args:
    creates: /home/deploy/.rbenv/versions/2.4.0-dev
  become_user: deploy

- name: set default ruby
  shell: bash -lc "rbenv global 2.4.0-dev"
  args:
    creates: /home/deploy/.rbenv/version
  become_user: deploy

- name: create .gemrc
  copy: src=.gemrc dest=/home/deploy/.gemrc
  become_user: deploy

- name: install bundler
  gem: name=bundler state=latest executable=/home/deploy/.rbenv/shims/gem user_install=no
  become_user: deploy
